name: ClickCopyChat
main: com.example.clickcopychat.ClickCopyChat
version: 1.0.2
api-version: '1.21'
author: you
description: Make chat messages clickable to copy their content to clipboard.
softdepend: [ProtocolLib, Essentials]
